Improved running commands for dev environment

diff --git a/src/main/resources/fakecmd/uberspace b/src/main/resources/fakecmd/uberspace
--- a/src/main/resources/fakecmd/uberspace
+++ b/src/main/resources/fakecmd/uberspace
@@ -1,4 +1,5 @@
-***REMOVED***!/usr/bin/env bash
+***REMOVED***!/bin/bash -x
+trap 'echo "$BASH_COMMAND" failed with error code $?' ERR
 
 ***REMOVED*** fake uberspace commands for testing
 
@@ -6,19 +7,4 @@ subCat=$1           ***REMOVED*** web
 subSubCat=$2        ***REMOVED*** domain / backend
 subSubSubCat=$3     ***REMOVED*** list
 
-if [[ "$subCat" = "web" ]]
-then
-    if [[ "$subSubCat" = "domain" ]]
-    then
-        if [[ "$subSubSubCat" = "list" ]]
-        then
-            cat "$(dirname "$0")/output_uberspace_web_domain_list.txt"
-        fi
-    elif [[ $subSubCat = "backend" ]]
-    then
-        if [[ "$subSubSubCat" = "list" ]]
-        then
-            cat "$(dirname "$0")/output_uberspace_web_backend_list.txt"
-        fi
-    fi
-fi
+cat "output_$0_$1_$2_$3.txt"
